Repository ashatat/e-commerce, pull requests merged in 2018-11, with the labels that each got.

#52 Input field component
  client/src/components/common/InputField/index.jsx
Labels: awaiting-review

#64 adds exception for windows linebreaks
  client/.eslintrc.js
Labels: awaiting-review

#71 adding normalize.css + App.css
  client/src/App.css
  client/src/App.jsx
  client/src/Normalize.css
Labels: approved

#59 Fix the tag component
  client/src/components/common/Tag/Tag.css
  client/src/components/common/Tag/Tag.jsx
  client/src/components/common/Tag/Tag.test.js
  client/src/components/common/Tag/__snapshots__/Tag.test.js.snap
Labels: approved

#69 Add google fonts
  client/public/index.html
Labels: awaiting-review

#67 Refactor input field
  client/public/index.html
  client/src/components/common/InputField/index.jsx
Labels: approved

#72 adds react-router to the dependencies of the project
  client/package-lock.json
  client/package.json
Labels: awaiting-review

#81 delete an extra . from the className property
  client/src/components/common/Tag/Tag.jsx
  client/src/components/common/Tag/__snapshots__/Tag.test.js.snap
Labels: awaiting-review, bug

#51 Create item-view picture
  client/src/components/ItemPic/ItemPic.css
  client/src/components/ItemPic/ZoomImg.jsx
  client/src/components/ItemPic/index.jsx
Labels: awaiting-review

#87 initial draft of the collaboration rules
  COLLAB_RULES.md
Labels: approved

#82 Refactor the input field component
  client/src/components/common/InputField/index.jsx
Labels: approved, urgent

#84 Signup form
  client/src/App.jsx
  client/src/components/SignUp/SignUp.css
  client/src/components/SignUp/index.jsx
Labels: approved

#85 Login form
  client/src/App.jsx
  client/src/components/Login/Login.css
  client/src/components/Login/index.jsx
  client/src/components/common/InputField/index.jsx
Labels: approved

#95 React icons
  client/package-lock.json
  client/package.json
Labels: urgent
